# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/ubuntu-server-2004-lts"
  config.vm.hostname = "server-dbc"
  config.vm.provider "VirtualBox" do |vb|
   vb.name = "ubuntu server"
   vb.memory = 2048
   vb.cpus = 2
  end
  config.vm.synced_folder "/data", "PR0101"
end
