Vagrant.configure("2") do |config|
    config.vm.define "server1" do |m1|
        m1.vm.box = "StefanScherer/windows_2019"
        m1.vm.hostname = "server1"
        config.vm.provider "VirtualBox" do |vb|
            vb.memory = 4096
            vb.cpus = 4
        end
        config.vm.network "private_network", ip: "172.16.5.10"
        config.vm.network "forwarded_port", guest: 22, host: 22000
    end
    config.vm.define "server2" do |m2|
        m2.vm.box = "gusztavvargadr/windows-10"
        m2.vm.hostname = "server2"
        config.vm.provider "VirtualBox" do |vb|
            vb.memory = 2048
            vb.cpus = 2
        end
        config.vm.network "private_network", ip: "172.16.5.20"
        config.vm.network "forwarded_port", guest: 22, host: 23000
    end   
end